language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.1
  - 3.2
  - pypy
install:
  - pip freeze
script:
  - python pep8.py --testsuite testsuite
  - python pep8.py --statistics pep8.py
  - python pep8.py --doctest
matrix:
  allow_failures:
    - python: pypy
