rm -rf ./sources_plugins/supertab/.gitignore
rm -rf ./sources_plugins/vim-rails/.gitignore
rm -rf ./sources_plugins/flake8/.netrwhist
rm -rf ./sources_plugins/pep8/.gitignore
rm -rf ./autoload/.svn
rm -rf ./sources_non_forked/vim-coffee-script/.gitignore
rm -rf ./sources_non_forked/vim-surround/.gitignore
rm -rf ./sources_non_forked/vim-snipmate/.gitignore
rm -rf ./sources_non_forked/nerdtree/.gitignore
rm -rf ./sources_non_forked/ctrlp.vim/.gitignore
rm -rf ./sources_non_forked/vim-less/.gitignore
rm -rf ./sources_non_forked/vim-powerline/.gitignore
rm -rf ./sources_non_forked/ack.vim/.netrwhist
rm -rf ./sources_non_forked/ack.vim/.gitignore
rm -rf ./sources_non_forked/vim-addon-mw-utils/.gitignore
